version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  express-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - redis

  express-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: express-prod
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge
