export interface IPloomesResponse<T> {
    "@odata.context": string;
    value: T[];
}

export type IPloomesDealResponse = IPloomesResponse<IPloomesDeal>;
export type IPloomesContactResponse = IPloomesResponse<IPloomesContact>;
export type IPloomesPipelineResponse = IPloomesResponse<IPloomesPipeline>;

export interface IPloomesStatus {
    Id: number;
    Name: string;
}

export interface IPloomesDeal {
    Id: number;
    Title: string;
    AccountId: number;
    ContactId: number;
    ContactName: string;
    PersonId: number | null;
    PersonName: string | null;
    PipelineId: number;
    StageId: number;
    StatusId: number;
    FirstTaskId: number | null;
    FirstTaskDate: string;
    FirstTaskNoTime: boolean;
    HasScheduledTasks: boolean;
    TasksOrdination: number;
    ContactProductId: number | null;
    LastQuoteId: number | null;
    IsLastQuoteApproved: boolean;
    WonQuoteId: number | null;
    LastStageId: number | null;
    LossReasonId: number | null;
    OriginId: number | null;
    OwnerId: number | null;
    StartDate: string;
    FinishDate: string | null;
    CurrencyId: number;
    Amount: number;
    StartCurrencyId: number;
    StartAmount: number;
    Read: boolean;
    LastInteractionRecordId: number | null;
    LastOrderId: number | null;
    DaysInStage: number;
    HoursInStage: number;
    Length: number;
    CreateImportId: number | null;
    UpdateImportId: number | null;
    LeadId: number | null;
    OriginDealId: number | null;
    ReevId: number | null;
    Editable: boolean;
    Deletable: boolean;
    CreatorId: number;
    UpdaterId: number;
    CreateDate: string;
    LastUpdateDate: string;
    LastDocumentId: number | null;
    DealNumber: number;
    ImportationIdCreate: number | null;
    ImportationIdUpdate: number | null;
    PublicFormIdCreate: number | null;
    PublicFormIdUpdate: number | null;
    MergeStatus: number | null;
    PriorityId: number | null;
    FieldStatusId: number | null;
    IsRead: boolean;
    WasMerged: number | null;
    Status: IPloomesStatus;
}

export interface IPloomesContact {
    Id: number;
    TypeId: number;
    Name: string;
    LegalName: string | null;
    Register: string | null;
    CNPJ: string | null;
    CPF: string | null;
    StatusId: number;
    CompanyId: number | null;
    RelationshipId: number | null;
    LineOfBusinessId: number | null;
    OriginId: number | null;
    NumberOfEmployeesId: number | null;
    ClassId: number;
    OwnerId: number;
    Birthday: string | null;
    NextAnniversary: string | null;
    PreviousAnniversary: string | null;
    Note: string | null;
    Email: string;
    Website: string | null;
    RoleId: number | null;
    DepartmentId: number | null;
    Skype: string | null;
    Facebook: string | null;
    StreetAddress: string | null;
    StreetAddressNumber: string | null;
    StreetAddressLine2: string | null;
    Neighborhood: string | null;
    ZipCode: string | null;
    ForeignZipCode: string | null;
    ForeignZipCodeCountryId: number | null;
    ForeignZipCodeWithoutMask: string | null;
    CityId: number | null;
    StateId: number | null;
    CountryId: number | null;
    CurrencyId: number | null;
    EmailMarketing: boolean | null;
    CNAECode: string | null;
    CNAEName: string | null;
    CNAESecondary: string | null;
    Latitude: number | null;
    Longitude: number | null;
    ImportId: number | null;
    CreateImportationId: number | null;
    UpdateImportationId: number | null;
    FirstTaskId: number | null;
    FirstTaskDate: string;
    LastInteractionRecordId: number | null;
    LastDealId: number;
    LastOrderId: number;
    TasksOrdination: number;
    LeadId: number | null;
    Editable: boolean;
    Deletable: boolean;
    CreatorId: number;
    UpdaterId: number;
    CreateDate: string;
    LastUpdateDate: string;
    Key: string | null;
    LastDocumentId: number | null;
    AvatarUrl: string | null;
    LastCompanyId: number | null;
    IdentityDocument: string | null;
    HasScheduledTasks: boolean;
    ImportationIdCreate: number | null;
    ImportationIdUpdate: number | null;
    PublicFormIdCreate: number | null;
    PublicFormIdUpdate: number | null;
}

export interface IPloomesPipeline {
    Id: number;
    Name: string;
    FormId: number;
    QuickFormId: number;
    MustPassAllStages: boolean;
    ForbiddenStageReturn: boolean;
    MayCreateQuotes: boolean;
    MayCreateOrders: boolean;
    MayCreateDocuments: boolean;
    MayWinDeals: boolean;
    MayLoseDeals: boolean;
    Archived: boolean;
    NewOrderOnWonDeal: boolean;
    CreateOrderOnWonDeal: boolean;
    WinDealOnLastStage: boolean;
    SingularUnitName: string;
    PluralUnitName: string;
    GenderId: number;
    DefaultQuoteDocumentTemplateId: number | null;
    DefaultOrderDocumentTemplateId: number | null;
    DefaultDocumentDocumentTemplateId: number | null;
    Color: string;
    IconId: number;
    EnableTableViewMode: boolean;
    EnableFunnelViewMode: boolean;
    NoAllowedPipelines: number | null;
    WinButtonId: number;
    LoseButtonId: number;
    WinVerbId: number;
    LoseVerbId: number;
    Ordination: number;
    ViewMode: string | null;
    LastUpdateDate: string;
    ContactPageTableId: number;
    QuotesUseERPFormat: boolean | null;
    OrdersUseERPFormat: boolean | null;
    DocumentsUseERPFormat: boolean | null;
    ExecuteAutomationsAsAutomationUser: boolean | null;
    CanMergeDeals: boolean | null;
    EnableStatus: boolean | null;
    EnableDealsRead: boolean | null;
    CanPerformPolling: boolean | null;
}
